podcast/config/routes.rb
Rails.application.routes.draw do

	devise_for :users

	resources :users, only: [:index, :show] do
		resources :episodes
	end

	authenticated :user do 
		root 'users#dashboard', as: "authenticated_root"
	end

	root 'welcome#index'
end

podcast/app/models/episode.rb
class Episode < ActiveRecord::Base
  belongs_to :user
end

podcast/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :episodes
end

podcast/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected 

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :current_password, :title, :description, :itunes, :stitcher, :podbay])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:email, :password, :password_confirmation, :title])
  end
end

podcast/app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
	before_action :find_user
	before_action :find_episode


	def new 
		@episode = @user.episodes.new
	end

	def edit

	end

	def update
		if @episode.update episode_params
			redirect_to user_episode_path(@user, @episode), notice: "Episode updated"
		else
			render 'new'
		end
	end

	def destroy
		@episode.destroy
		redirect_to root_path
	end

	def create 
		@episode = @user.episodes.new episode_params
		if @episode.save
			redirect_to user_episode_path(@user, @episode)
		else
			render 'edit'
		end
	end

	def show
		@episodes = Episode.where(user_id: @user).order("created_at DESC").reject { |e|	e.id == @episode.id }
	end

	private

	def episode_params
		params.require(:episode).permit(:title, :description)
	end

	def find_user
		@user = User.find(params[:user_id])
	end

	def find_episode
		if params[:id].nil?
			@episode = current_episode
		else
			@episode = Episode.find(params[:id])
		end
	end
end

podcast/app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :find_user, only: [:show, :dashboard]
	before_action :find_episode, only: [:show, :dashboard]
	def index
		@users = User.all.order("created_at DESC")
	end

	def show
		
	end

	def dashboard 

	end

	private

	def find_user
		if params[:id].nil?
			@user = current_user
		else
			@user = User.find(params[:id])
		end
	end

	def find_episode
		@episodes = Episode.where(user_id: @user).order("created_at DESC")
	end
end

podcast/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index

	end
end

podcast/app/helpers/episodes_helper.rb
module EpisodesHelper
end

podcast/app/helpers/podcasts_helper.rb
module PodcastsHelper
end

podcast/app/helpers/users_helper.rb
module UsersHelper
end

podcast/app/helpers/welcome_helper.rb
module WelcomeHelper
end

podcast/app/views/episodes/_form.html.erb
<%= form_for([@user, @episode]) do |f| %>
<div class="field">
	<%= f.label :title  %> <br>
	<%= f.text_field :title %>
</div>
<div class="field">
	<%= f.label :description %>
	<%= f.text_area :description %>
</div>
<%= f.submit class: "button button_highlight button_block" %>

<% end %>

podcast/app/views/episodes/edit.html.erb
<div id="podcast_show">
	<div id="show_banner">
		<div class="wrapper">
			<h1>The RocketShip Podcast Dashboard</h1>
		</div>
	</div>

	<div id="links">
		<div class="wrapper_skinny">
			<ul>
				<li><%= link_to 'Episodes', authenticated_root_path  %></li>
				<li><%= link_to 'New Episode', new_user_episode_path(@user) %></li>
				<li><%= link_to 'Account Setting', edit_user_registration_path  %></li>
				<li><%= link_to 'View Podcast', user_path(@user)  %></li>
			</ul>
		</div>
	</div>

	<div id="form">
		<div class="wrapper_skinny">
			<%= render 'form' %>
		</div>
	</div>
</div>

podcast/app/views/episodes/new.html.erb
<div id="podcast_show">
	<div id="show_banner">
		<div class="wrapper">
			<h1>The RocketShip Podcast Dashboard</h1>
		</div>
	</div>

	<div id="links">
		<div class="wrapper_skinny">
			<ul>
				<li><%= link_to 'Episodes', authenticated_root_path  %></li>
				<li><%= link_to 'New Episode', new_user_episode_path(@user) , class: "current"  %></li>
				<li><%= link_to 'Account Setting', edit_user_registration_path  %></li>
				<li><%= link_to 'View Podcast', user_path(@user)  %></li>
			</ul>
		</div>
	</div>

<div id="form">
	<div class="wrapper_skinny">
		<div class="field">
			<%= form_for([@user, @episode]) do |f| %>
			<%= f.label :title  %> <br>
			<%= f.text_field :title %>
		</div>
		<div class="field">
			<%= f.label :description %>
			<%= f.text_area :description %>
		</div>
		<%= f.submit class: "button button_highlight button_block" %>

		<% end %>

	</div>
</div>
</div>

podcast/app/views/episodes/show.html.erb
<div id="podcast_show">
	<div id="show_banner">
		<div class="wrapper_skinny">
		<h1><%= @user.title %></h1>
			<p id="description">
				<%= @user.description %>
			</p>
			<% unless @user.itunes.blank? %>
				<a href="<%= @user.itunes %>" target="_blank" class="subscribe_button">iTunes</a>
			<% end %>

			<% unless @user.stitcher.blank? %>
				<a href="<%= @user.stitcher %>" target="_blank" class="subscribe_button">Stitcher</a>
			<% end %>

			<% unless @user.podbay.blank? %>
				<a href="<%= @user.podbay %>" target="_blank" class="subscribe_button">PodBay</a>
			<% end %>
		</div>
	</div>

	<div id="breadcrumb">
		<%= link_to users_path do %>
			all podcasts
		<% end %>
		<span>/</span>
		<%= link_to user_path(@user) do %>
			<%= @user.title %>
		<% end %>
		<span>/</span>
		<%= @episode.title %>
	</div>

	<div id="episode_content">
		<div class="wrapper_skinny">
			<img src="images/seenwes.svg" class="current_episode_thumbnail" alt="">
			<h2><%= @episode.title %></h2>
			<p class="description">
			<%= @episode.description %>
			</p>
		</div>
	</div>

	<div id="episodes">
		<div class="wrapper_skinny">
			<ul class="cf">
				<% @episodes.each do |episode| %>
					<li class="cf">
						<div class="episode_thumbnail">
							<a href="#">
								<img src="images/seenwes.svg" alt="">
							</a>
						</div>
						<div class="episode_overview">
							<h2><%= link_to episode.title, user_episode_path(@user, episode) %></h2>
							<p class="description">
								<%= episode.description %>
							</p>
						</div>
					</li>
				<% end %>
				<!-- end episode -->
			</ul>
		</div>
	</div>
</div>
<div class="pagination">
	<span class="previous_page disabled">Previous</span>
	<em class="current">1</em>
	<a href="#">2</a>
	<a href="#" class="next_page">Next</a>
</div>

podcast/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Files</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if alert %>
       <p class="alert">
       <%= alert %>	
       </p>
<% elsif notice %>
	<p class="notice">
	<%= notice %>
	</p>
<% end %>

<header id="main_header" class="cf">
  <div class="wrapper_wide">
  <%= link_to 'Podcast.fm', root_path, id: "logo" %>
    <nav>
      <ul>
        <% unless user_signed_in? %>
        <li><%= link_to 'Explore', users_path %></li>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <li><%= link_to 'Create a Podcast', new_user_registration_path %></li>
      <% else %>
        <li><%= link_to 'Dashboard', authenticated_root_path %></li>
        <li><%= link_to 'Explore', users_path %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
      <% end %>
      </ul>
    </nav>
    </div>
    </header>

<%= yield %>

</body>
</html>

podcast/app/views/users/dashboard.html.erb
  <div id="podcast_show">
    <div id="show_banner">
      <div class="wrapper">
        <h1>The RocketShip Podcast Dashboard</h1>
      </div>
    </div>

    <div id="links">
      <div class="wrapper_skinny">
        <ul>
          <li><%= link_to 'Episodes', authenticated_root_path , class: "current"  %></li>
          <li><%= link_to 'New Episode', new_user_episode_path(@user)  %></li>
          <li><%= link_to 'Account Setting', edit_user_registration_path  %></li>
          <li><%= link_to 'View Podcast', user_path(@user)  %></li>
        </ul>
      </div>
    </div>

    <div id="episodes">
      <div class="wrapper_skinny">
        <ul class="cf">
          <% @episodes.each do |episode| %>
          <li class="cf">
            <div class="episode_thumbnail">
              <a href="#">
                <img src="images/seenwes.svg" alt="">
              </a>
            </div>
            <div class="episode_overview">
              <h2><%= link_to episode.title, user_episode_path(@user, episode) %></h2>
              <p class="description">
                <%= episode.description %>
              </p>
              <div class="authorized_links">
                <%= link_to "Edit", edit_user_episode_path(@user, episode) %>
                <%= link_to "Delete", user_episode_path(@user, episode), method: :delete, data: {confirm: "Are you sure ?"} %>
              </div>
            </div>
          </li>
          <% end %>
          <!-- end episode -->
        </ul>
      </div>
    </div>

    <div class="pagination">
    <span class="previous_page disabled">Previous</span>
    <em class="current">1</em>
    <a href="#">2</a>
    <a href="#" class="next_page">Next</a>
  </div>

  </div>

podcast/app/views/users/index.html.erb
<div id="banner" class="podcasts_banner">
	<h1>Discover your new favorite podcast</h1>
</div>
<div id="podcasts" class="cf">
	<div class="wrapper">
		<ul>
			<% @users.each do |user| %>
			<%= link_to user do %>
				<li>
					<img src="images/narwhales.jpg" alt="">
					<div class="podcast_overview">
					<h2><%= user.title %></h2>
					<p class="episode_count">1 Episode</p>
					</div>
				</li>
			<% end %>
			<% end %>
			</ul>
</div>
</div>
<div class="pagination">
	<span class="previous_page disabled">Previous</span>
	<em class="current">1</em>
	<a href="#">2</a>
	<a href="#" class="next_page">Next</a>
</div>

podcast/app/views/users/show.html.erb
<div id="podcast_show">
	<div id="show_banner">
		<div class="wrapper_skinny">
		<h1><%= @users.title %></h1>
			<p id="description">
				<%= @users.description %>
			</p>
			<% unless @users.itunes.blank? %>
				<a href="<%= @users.itunes %>" target="_blank" class="subscribe_button">iTunes</a>
			<% end %>

			<% unless @users.stitcher.blank? %>
				<a href="<%= @users.stitcher %>" target="_blank" class="subscribe_button">Stitcher</a>
			<% end %>

			<% unless @users.podbay.blank? %>
				<a href="<%= @users.podbay %>" target="_blank" class="subscribe_button">PodBay</a>
			<% end %>
		</div>
	</div>

	<div id="breadcrumb">
		<%= link_to users_path do %>
			all podcasts
		<% end %>
		<span>/</span>
		<a href="#">The Rocketship Podcast</a>
	</div>

	<div id="episodes">
		<div class="wrapper_skinny">
			<ul class="cf">
				<li class="cf">
					<div class="episode_thumbnail">
						<a href="#">
							<img src="images/seenwes.svg" alt="">
						</a>
					</div>
					<div class="episode_overview">
						<h2><a href="episode.html">The Episode Title Goes Here</a></h2>
						<p class="description">
							Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus, dolor dolore nemo quaerat ex at qui beatae totam placeat deserunt, illum vel, nisi, explicabo aut magnam voluptas eius assumenda modi?
						</p>
					</div>
				</li>
				<!-- end episode -->
				<li class="cf">
					<div class="episode_thumbnail">
						<a href="#">
							<img src="images/seenwes.svg" alt="">
						</a>
					</div>
					<div class="episode_overview">
						<h2><a href="#">The Episode Title Goes Here</a></h2>
						<p class="description">
							Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus, dolor dolore nemo quaerat ex at qui beatae totam placeat deserunt, illum vel, nisi, explicabo aut magnam voluptas eius assumenda modi?
						</p>
					</div>
				</li>
				<!-- end episode -->
				<li class="cf">
					<div class="episode_thumbnail">
						<a href="#">
							<img src="images/seenwes.svg" alt="">
						</a>
					</div>
					<div class="episode_overview">
						<h2><a href="#">The Episode Title Goes Here</a></h2>
						<p class="description">
							Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus, dolor dolore nemo quaerat ex at qui beatae totam placeat deserunt, illum vel, nisi, explicabo aut magnam voluptas eius assumenda modi?
						</p>
					</div>
				</li>
				<!-- end episode -->
			</ul>
		</div>
	</div>
</div>
<div class="pagination">
	<span class="previous_page disabled">Previous</span>
	<em class="current">1</em>
	<a href="#">2</a>
	<a href="#" class="next_page">Next</a>
</div>

podcast/app/views/welcome/index.html.erb
<div id="background">
	<header class="cf">
	<div class="wrapper_wide">
		<%= link_to 'Podcast.fm', root_path, id: "logo" %>
		<nav>
			<ul>
			<% unless user_signed_in? %>
				<li><a href="#">Explore</a></li>
				<li><%= link_to 'Sign In', new_user_session_path %></li>
				<li><a href="#">Create a Podcast</a></li>
			<% else %>
				<li><a href="#">Explore</a></li>
				<li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
			<% end %>
			</ul>
		</nav>
		<div>
	</header>
	<h1>Discover your new favorite<br>podcast, or create your own.</h1>
	<%= link_to 'Create a Podcast', new_user_registration_path, class: "button button_highlight" %>
    	<%= link_to 'Explore', users_path, class: "button button_white" %>
</div>