TravelApp/config/routes.rb
Rails.application.routes.draw do
    get '/tags' => 'tags#index'
    get '/tags/:id' => 'tags#show', as: :tag
    get '/destinations/:id' => 'destinations#show', as: :destination
    get '/destinations/:id/edit' => 'destinations#edit', as: :edit_destination 
patch '/destinations/:id' => 'destinations#update'

end

TravelApp/app/models/destination.rb
class Destination < ActiveRecord::Base
    belongs_to :tag
end

TravelApp/app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :destinations
end

TravelApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

TravelApp/app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
    def show
    @destination = Destination.find(params[:id])
  end
  def edit 
  @destination = Destination.find(params[:id]) 
end

def update 
  @destination = Destination.find(params[:id]) 
  if @destination.update_attributes(destination_params) 
    redirect_to(:action => 'show', :id => @destination.id) 
  else 
    render 'edit' 
  end 
end

private 
  def destination_params 
    params.require(:destination).permit(:name, :description) 
  end
end

TravelApp/app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		@tags = Tag.all
	end
	def show 
  @tag = Tag.find(params[:id]) 
  @destinations = @tag.destinations 
end
end

TravelApp/app/helpers/application_helper.rb
module ApplicationHelper
end

TravelApp/app/helpers/destinations_helper.rb
module DestinationsHelper
end

TravelApp/app/helpers/tags_helper.rb
module TagsHelper
end

TravelApp/app/views/destinations/edit.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="destination">
  <div class="container">
    <%= image_tag @destination.image %>
    
    <!-- Your code here -->
<%= form_for(@destination) do |f| %>  
  <div class="field"> 
    <%= f.text_field :name %><br> 
    <%= f.text_field :description %> 
    <%= f.submit "Update", :class => "btn" %>
<% end %>
  </div>
</div> 

TravelApp/app/views/destinations/show.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="destination">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <%= image_tag @destination.image %>
        <h2><%= @destination.name %></h2>
        <p><%= @destination.description %></p>
        <%= link_to 'Edit', edit_destination_path(@destination) %>
      </div>
    </div>
  </div>
</div> 

TravelApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

TravelApp/app/views/tags/index.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="tags">
  <div class="container">
    <div class="cards row">
    	<% @tags.each do |t| %>
      <div class="card col-xs-4">
        <%= image_tag t.image %>
        <h2><%= t.title %></h2>
        <%= link_to "Learn more", tag_path(t) %>
      </div>
      <% end %>
    </div>
  </div>
</div>

TravelApp/app/views/tags/show.html.erb
<div class="header">
  <div class="container">
    <img src="http://s3.amazonaws.com/codecademy-content/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>BokenjiKan</h1>
  </div>
</div>

<div class="tag">
  <div class="container">
    <h2><%= @tag.title %></h2>

    <div class="cards row">
      <% @destinations.each do |d| %>
      <div class="card col-xs-4">
        <%= image_tag d.image %>
        <h2><%= d.name %></h2>
        <p><%= d.description %></p>
        <%= link_to "See more", destination_path(d) %>
      </div>
      <% end %>
    </div>

  </div>
</div>